FROM postgres:15

RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-15-postgis-3 -y \
    && apt-get install postgis -y

COPY ./docker_postgres_init.sql /docker-entrypoint-initdb.d/docker_postgres_init.sql
